### ISSUE TITLE
Issues running on a 0.3.7 release.

### ISSUE THREAD

**Issue by rohitvarkey** [SimonDanisch/FixedSizeArrays.jl#4]
Hello, 

I've been trying to get this to run on a 0.3.7 release. At first I got a error for `AbstractString not being defined`. So I added `using Compat` to the `FixedSizeArrays.jl` file. But even after that I'm getting this error.

``` julia
ERROR: syntax: extra token "call" after end of expression
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /home/rohitvarkey/.julia/v0.3/FixedSizeArrays/src/constructors.jl, in expression starting on line 52
while loading /home/rohitvarkey/.julia/v0.3/FixedSizeArrays/src/FixedSizeArrays.jl, in expression starting on line 6
```

Regards,
Rohit.

**Comment by SimonDanisch** [comment]
Hi Rohit,
this is 0.4 only, sorry about this.
I'm thinking about a compatibility mode for 0.3, but just if it's really needed.
Over at compose3D I just wanted to get the discussion running, to see what FixedSizeArrays will need in order to make it usable (I've already added all features that I need for GLVisualize).

Best,
Simon

**Comment by rohitvarkey** [comment]
Hi Simon,

I kind of figured that. Just wanted to let you know just in case! 

I'll get a 0.4 version and check it out. I'm still not exactly sure how FixedSizeArrays and GeometryTypes work. Will play around with it a bit and get back to you!

Also I haven't checked Compose3D on 0.4.  Have to do that too.

I guess this can be issue closed then. :smile:

Regards,
Rohit.

**Comment by SimonDanisch** [comment]
Great!
Well, FixedSizeArrays is giving any composite type array like behavior by inheriting from FixedSizeArrays.
So you can do something like this:

``` Julia
immutable Vec3{T} <: FixedSizeVector{T, 3}
r::T
g::T
b::T
end
Vec3(0) # constructor with 0 argument already defined. Actually, this only works if you created them
#  with @gen_fixed_size_vector, due to ambiguity issues :(
rand(Vec3{Int})+sin(Vec3(0,2,2)) # a lot of array functions are already defined
immutable Mat3x3{T} FixedMatrix{T, 3,3}
v_1::T
...
v_9::T
end
eye(Mat3x3{Float32}) * rand(Vec3{Float32}) # will also "just work"
```

This is expendable to a lot of other areas.
You can define color types (see ColorTypes.jl) the same way, and arbitrary other point types like normals, vertices etc.
As they all inherit from FixedSizeArray, it's very easy to handle them in the same way. So I'm using this for my GPU array types, which can take any fixedsizearray, if its a color, a point or what not, because I can be sure that all the important functions are defined.
Also I can do some cool stuff in MeshIO ;)
And because it's so easy to define different types like Point3 or Normal3, I can create customized visualizations for these types via multiple dispatch. 
Without FixedSizeArrays, this would end up in a lot of types which would all need to define the same functions over and over again.

Best,
Simon
