### ISSUE TITLE
infinite loop on constructing Vec{2}(0,0)

### ISSUE THREAD

**Issue by goretkin** [SimonDanisch/FixedSizeArrays.jl#56]
I don't know if it's supposed to work. I'm on Julia Version 0.4.1-pre+8

```
julia> Pkg.installed()["FixedSizeArrays"]
v"0.0.6"

julia> using FixedSizeArrays

julia> Vec(0,0)
FixedSizeArrays.Vec{2,Int64}((0,0))

julia> Vec{2}(0,0)
^CERROR: InterruptException:
 in call at /Users/goretkin/.julia/v0.4/FixedSizeArrays/src/constructors.jl:89 (repeats 9 times)
 in call at /Users/goretkin/.julia/v0.4/FixedSizeArrays/src/constructors.jl:84

(I can't reliably use Ctrl-C to interrupt this operation)
```

**Comment by sjkelly** [comment]
I can reproduce this on master. I don't see any reason as to why this shouldn't work. Patch incoming.

**Comment by sjkelly** [comment]
Err... it seems like this one is held up by https://github.com/julialang/julia/issues/12814

**Comment by SimonDanisch** [comment]
Stack overflows on different occasions get on my nerves as well... It's because the code for the constructors is pretty horrible and starts calling itself for cases that I don't handle.
I made a first move to tackle this in #58 .... It's not done yet, but I need to concentrate on other things today.

Best,
Simon

**Comment by mschauer** [comment]
:+1:
